FROM resin/%%RESIN_MACHINE_NAME%%-python


# RUN apt-get update && apt-get install  --fix-missing  -yq --no-install-recommends \
#     psmisc \
#     xorg \
#     mate-desktop-environment && \
#     apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable systemd init system in the container, so it never closes
ENV INITSYSTEM on

# Start.sh will run when the container starts
CMD startx
